const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function visible(el){if(!el)return false;const r=el.getBoundingClientRect();const s=getComputedStyle(el);return r.width>0&&r.height>0&&s.visibility!=='hidden'&&s.display!=='none';}
async function waitFor(fn,timeout=20000,step=250){const end=Date.now()+timeout;while(Date.now()<end){try{const v=fn();if(v)return v;}catch(e){}await sleep(step);}return null;}
function pageNeedsLogin(){const u=location.href.toLowerCase();if(u.includes('/checkpoint'))return 'checkpoint';if(u.includes('/login')||document.querySelector('input[name="email"],input[name="pass"]'))return 'login';return '';}
function textOf(el){return (el?.innerText||el?.textContent||'').replace(/\s+/g,' ').trim();}
function findComposerTrigger(){const els=[...document.querySelectorAll('[role="button"],div[tabindex="0"]')].filter(visible);const needles=['bạn viết gì đi','viết gì đó','write something','create a public post'];for(const el of els){const t=textOf(el).toLowerCase();if(needles.some(n=>t.includes(n)))return el;}return null;}
function findDialog(){const ds=[...document.querySelectorAll('div[role="dialog"]')].filter(visible);for(const d of ds){if(d.querySelector('[contenteditable="true"]'))return d;}return ds[ds.length-1]||null;}
async function openComposer(){let d=findDialog();if(d)return d;const trigger=await waitFor(findComposerTrigger,15000);if(!trigger)throw new Error('Không tìm thấy ô tạo bài viết trong Group.');trigger.click();d=await waitFor(findDialog,15000);if(!d)throw new Error('Không mở được cửa sổ Tạo bài viết.');return d;}
async function fillText(dialog,content){const selectors=['[contenteditable="true"][data-lexical-editor="true"]','[role="textbox"][contenteditable="true"]','[contenteditable="true"][role="textbox"]','div[contenteditable="true"]'];let box=null;for(const sel of selectors){box=[...dialog.querySelectorAll(sel)].find(visible);if(box)break;}if(!box)throw new Error('Không tìm thấy ô nhập nội dung.');box.focus();document.execCommand('selectAll',false,null);document.execCommand('insertText',false,content);box.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText',data:content}));await sleep(500);}
function b64ToFile(item){const bin=atob(item.base64);const bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);return new File([bytes],item.name||'image.jpg',{type:item.mime||'image/jpeg'});}
async function attachImages(dialog,images){if(!images?.length)return;let input=dialog.querySelector('input[type="file"]');if(!input){const controls=[...dialog.querySelectorAll('[role="button"],button,div[tabindex="0"]')].filter(visible);const btn=controls.find(el=>/ảnh\/?video|photo\/?video/i.test(textOf(el)));if(btn){btn.click();await sleep(900);input=dialog.querySelector('input[type="file"]');}}
if(!input)throw new Error('Không tìm thấy ô upload ảnh.');const dt=new DataTransfer();for(const item of images)dt.items.add(b64ToFile(item));input.files=dt.files;input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}));await sleep(Math.max(3500,images.length*1800));}
async function clickPost(dialog){const candidates=[...dialog.querySelectorAll('[role="button"],button')].filter(visible);let btn=candidates.find(el=>/^(đăng|post)$/i.test(textOf(el)));if(!btn)btn=candidates.find(el=>/\bđăng\b|\bpost\b/i.test(textOf(el)));if(!btn)throw new Error('Không tìm thấy nút Đăng.');const ready=await waitFor(()=>!btn.hasAttribute('aria-disabled')&&btn.getAttribute('aria-disabled')!=='true'&&!btn.disabled,30000);if(!ready)throw new Error('Nút Đăng chưa sẵn sàng.');btn.click();const gone=await waitFor(()=>!document.contains(dialog)||!visible(dialog),60000,500);if(!gone)throw new Error('Đã bấm Đăng nhưng cửa sổ tạo bài chưa đóng.');}
async function postCurrentGroup(payload){const state=pageNeedsLogin();if(state==='checkpoint')return {ok:false,code:'checkpoint',error:'Facebook yêu cầu checkpoint/xác minh.'};if(state==='login')return {ok:false,code:'login',error:'Facebook chưa đăng nhập.'};await sleep(1800);const dialog=await openComposer();await fillText(dialog,payload.content||'');await attachImages(dialog,payload.images||[]);await clickPost(dialog);return {ok:true};}
chrome.runtime.onMessage.addListener((msg,sender,sendResponse)=>{if(msg?.type!=='FBPOST_POST')return;postCurrentGroup(msg).then(sendResponse).catch(e=>sendResponse({ok:false,error:e?.message||String(e)}));return true;});