const $=id=>document.getElementById(id);
const ui={server:$('server'),code:$('code'),connect:$('connect'),check:$('check'),facebook:$('facebook'),disconnect:$('disconnect'),status:$('status'),message:$('message')};
function normalizeServer(v){return String(v||'').trim().replace(/\/+$/,'');}
async function config(){return await chrome.storage.local.get(['serverOrigin','deviceId','token','customerId']);}
function msg(t){ui.message.textContent=t||'';}
async function refresh(){const c=await config();ui.server.value=c.serverOrigin||ui.server.value||'';if(!c.deviceId||!c.token){ui.status.className='status offline';ui.status.innerHTML='<span></span><div><strong>Chưa liên kết</strong><small>Tạo mã trên website rồi nhập vào đây</small></div>';return;}try{const r=await chrome.runtime.sendMessage({type:'GET_STATUS'});if(r?.ok){ui.status.className='status online';ui.status.innerHTML=`<span></span><div><strong>Connector online</strong><small>Facebook: ${r.facebookLoggedIn?'đã đăng nhập':'chưa đăng nhập'} • ${r.deviceName||'Chrome'}</small></div>`;}else throw new Error(r?.error||'Không kiểm tra được');}catch(e){ui.status.className='status offline';ui.status.innerHTML='<span></span><div><strong>Đã liên kết nhưng chưa kiểm tra được</strong><small>Mở website hoặc bấm KIỂM TRA NGAY</small></div>';}}
ui.connect.onclick=async()=>{const server=normalizeServer(ui.server.value);const code=ui.code.value.trim().toUpperCase();if(!server||!code){msg('Nhập URL website và mã liên kết.');return;}ui.connect.disabled=true;msg('Đang liên kết...');try{const r=await fetch(server+'/api/extension/pair',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code,device_name:`Chrome • ${navigator.platform||'Desktop'}`,extension_version:chrome.runtime.getManifest().version})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Liên kết thất bại');await chrome.storage.local.set({serverOrigin:server,deviceId:d.device_id,token:d.token,customerId:d.customer_id});ui.code.value='';msg('Đã liên kết thành công.');await chrome.runtime.sendMessage({type:'POLL_NOW'});await refresh();}catch(e){msg(e.message||String(e));}finally{ui.connect.disabled=false;}};
ui.check.onclick=async()=>{msg('Đang kiểm tra...');try{const r=await chrome.runtime.sendMessage({type:'POLL_NOW'});msg(r?.ok?'Đã kiểm tra.':(r?.error||'Không kiểm tra được.'));}catch(e){msg(String(e));}await refresh();};
ui.facebook.onclick=()=>chrome.tabs.create({url:'https://www.facebook.com/',active:true});
ui.disconnect.onclick=async()=>{await chrome.storage.local.remove(['deviceId','token','customerId']);msg('Đã xóa liên kết trên Chrome này.');await refresh();};
refresh();